### ISSUE TITLE
Code and data release

### ISSUE THREAD

**Issue by dHonerkamp** [PrieureDeSion/drive-any-robot#1]
Hi, I very much enjoyed reading your paper. 

In the paper you write that both the code and data will be made publicy available. I wanted to ask when you plan to do this or, if it is not cleaned yet, if it would be possible to already make them available privately to other researchers like myself in the meantime? That would be fantastic.

**Comment by VinMing** [comment]
已收到。

**Comment by robodhruv** [comment]
Hi @dHonerkamp and @VinMing,

Thanks for your interest in our work! We just released model checkpoints, training code, and example deployment on a TurtleBot2/LoCoBot robot. Hope you find this useful.
