### ISSUE TITLE
some question about create_topomap.py 

### ISSUE THREAD

**Issue by GaHooooo** [PrieureDeSion/drive-any-robot#12]
Hi, i try to deploy it with carla,and i collect the .bag file, and  i use 
`./create_topomap.sh topomap_test_name /home/gahho/code/drive-any-robot/deployment/topomaps/bags/test202301191036_2023-01-20-10-53-19.bag`
it occurs  some error 
and i use default 
`python create_topomap.py`
it occurs the same error

![图片](https://user-images.githubusercontent.com/50771851/213612527-84b928e6-37bc-4ead-9944-af790b8fbd4d.png)
thanks for your reply

**Comment by ajaysridhar0** [comment]
Hi @GaHooooo,

It looks like your version of python does not like how I am typing the input arguments. I think I fixed the issue, so try pulling from the main branch again. Let me know if the fix works!

**Comment by GaHooooo** [comment]
it works,thank !!!
