### ISSUE TITLE
Missing the odometry topic in the recording script

### ISSUE THREAD

**Issue by james-yoo** [PrieureDeSion/drive-any-robot#13]
Hi @PrieureDeSion,
As far as I know, rosbag should record image and odometry topics for deployment step. However, the following line only records the image topic. Is there anything I misunderstood?
https://github.com/PrieureDeSion/drive-any-robot/blob/905c7e3e304157f64e33e6a5aaa92e76aefc98d7/deployment/src/record_bag.sh#L25

**Comment by ajaysridhar0** [comment]
Hi @james-yoo, 

The topological graph only relies on the image observations as described in the GNM paper. The edge weights of the graph are computed via a temporal distance estimate from the policy rather than using odometry data. However, feel free to add any extra topics as needed.

**Comment by james-yoo** [comment]
Hi @ajaysridhar0,
Sorry for my misunderstood. Thanks for your feedback!
