### ISSUE TITLE
./create_topomap.sh Image with strange color 

### ISSUE THREAD

**Issue by GaHooooo** [PrieureDeSion/drive-any-robot#15]
I use carla to deploy gnm，the image which rosbag's camera：
![图片](https://user-images.githubusercontent.com/50771851/215448072-df2e1b84-fa9a-4131-9c81-a68ee577d33b.png)

the image ./create_topomap.sh create

![图片](https://user-images.githubusercontent.com/50771851/215448013-1fc352d1-3bf2-4da2-9ac8-b09705353778.png)

It looks different,that's right?
Thanks for you reply

**Comment by ajaysridhar0** [comment]
It looks like the image is in the BGR color format rather than the RGB color format with the ROS topic you are using. Can you try adding this line at the end of the `callback_obs()` function in the `drive-any-robot/deployment/src/create_topomap.py` file: 
```
img = img[:,:,::-1] # flip the color channels of the PIL Image
```
Let me know if this works or not.

**Comment by chungcode0218** [comment]
The code you provided solved my problem, thank you!
