### ISSUE TITLE
Minor bug in deployment side image_transform

### ISSUE THREAD

**Issue by lasuomela** [PrieureDeSion/drive-any-robot#16]
Hi,

Nice work! I've been testing the method, and ran into a bug in the deployment version of the image_transform function (https://github.com/PrieureDeSion/drive-any-robot/blob/main/deployment/src/utils.py#L89).

The order of image_size is flipped twice (lines 99, 103), resulting in the image_size being given to resize as WxH instead of HxW. In my experience this was affecting collision avoidance performance to some extent.

Br,
Lauri

**Comment by ajaysridhar0** [comment]
Hi Lauri,

Thank you for catching this bug! We just fixed it, but let me know if you find any other issues.

Best, 
Ajay
