### ISSUE TITLE
Some questions about running the project in the CARLA simulator

### ISSUE THREAD

**Issue by jmwang0117** [PrieureDeSion/drive-any-robot#18]
Hi
thanks for the great work ！
I tried to run your work in the CARLA simulator, but encountered some problems. 
First of all, whether I use lagre model or medium model, the car always turns in circles. What is the reason? Is the initial point of the car must be consistent with the initial point recorded by rosbag?
In addition, I found that the vehicle will not avoid obstacles when it encounters obstacles. Is it because this work does not add obstacle avoidance algorithms? Just pure path planning?
Finally, can you provide more information on how your work was run in the CARLA simulator?
Looking forward to your reply, thank you!

**Comment by robodhruv** [comment]
Hi,

Thanks for your interest in our work. GNM did not report results on CARLA so I do not have code regarding required modifications, but I would expect it to work reasonably (from experiments reported with ViNT). Could you describe your setup in detail?
- Are you just using the pre-trained model, or fine-tuning GNM?
- How are you passing subgoal images to GNM? I presume you are recording a rosbag; how are you converting that to the "topomap" required by GNM?
- How did you test collision avoidance with GNM? Is this independent of the "spinning in circles" behavior you mention?

If it's spinning in circles, my best guess is that the low-level tracking controller is not properly calibrated and is magnifying very small deltas in ypos, so the robot executes extremely high angular velocities.

**Comment by Cxf123Coder** [comment]
Hello, I also encountered the problem of being unable to avoid obstacles in gazebo and real machine tests. Have you solved this problem? What exactly causes this? Looking forward to your reply.
