### ISSUE TITLE
Question on data sampling rate

### ISSUE THREAD

**Issue by TimeEscaper** [PrieureDeSion/drive-any-robot#19]
Dear authors,

Thank you for the amazing work and releasing the datasets! I have a question regarding the RECON dataset. In the [process_bags.py](https://github.com/PrieureDeSion/drive-any-robot/blob/main/train/process_bags.py#L115) script the sample rate is set by default to 4 Hz. In the [process_recon.py](https://github.com/PrieureDeSion/drive-any-robot/blob/main/train/process_recon.py) script I didn't find anything related to the sample rate. Do you assume that the sample rate in the RECON dataset is also equal to 4 Hz?

Looking forward for your reply!

**Comment by robodhruv** [comment]
Yes, that seems to be implicit in this case. In follow-up work (https://github.com/robodhruv/visualnav-transformer), we have made this more intentional and hopefully easier to develop. Please let me know if you have any questions and sorry for the late response.
