### ISSUE TITLE
Code and data release

### ISSUE THREAD

**Issue by GaHooooo** [PrieureDeSion/drive-any-robot#2]
Hello author, I'm very interested in your research, thanks for your great job 
and I want to know when the code and data will go to open source？

**Comment by VinMing** [comment]
已收到。

**Comment by robodhruv** [comment]
Hi @GaHooooo,

Thanks for your interest in our work! We just released model checkpoints, training code, and example deployment on a TurtleBot2/LoCoBot robot. Hope you find this useful.
