### ISSUE TITLE
Is there documentation for a successful deployment in carla?

### ISSUE THREAD

**Issue by lizhiwen19900709** [PrieureDeSion/drive-any-robot#21]
Is there documentation for a successful deployment in carla?

**Comment by lizhiwen19900709** [comment]
The carla I used was 0.9.6

**Comment by robodhruv** [comment]
Sorry for the super late response, I did not receive notifications about this earlier.

We will provide a more complete response in this thread: https://github.com/robodhruv/visualnav-transformer/issues/14
