### ISSUE TITLE
The download link for the pre-trained weights has expired or is broken. Could you please provide a new link?

### ISSUE THREAD

**Issue by deavn2236** [PrieureDeSion/drive-any-robot#25]
The download link for the pre-trained weights has expired or is broken. Could you please provide a new link?

**Comment by Ryujikoyasu** [comment]
@robodhruv 
Could you please provide a new link?

**Comment by robodhruv** [comment]
Apologies, please use [this link](https://drive.google.com/file/d/1bzCPd_OsXjS2aGPTQladbI8ImxLZwrQh/view?usp=share_link)
