### ISSUE TITLE
Could not find Dijkstra’s algorithm

### ISSUE THREAD

**Issue by james-yoo** [PrieureDeSion/drive-any-robot#5]
Hi

Thank you for sharing great work! In the paper, I found that you used Dijkstra’s algorithm to compute the optimal sequence. However, I could not find any code related to Dijkstra’s algorithm in 'deployment' directory.

Please let me know if I missed anything.

**Comment by robodhruv** [comment]
Hi James,

As mentioned in the readme, this release prioritizes the GNM model that takes as input a sequence of images and _tracks_ it to the goal using a learned policy. While planning is an important aspect of the problem, the current repo is focused on the post-planning step, and it should be possible to integrate your favorite planner (e.g., Dijkstra's) with the GNM following the plan at a low-level. Please let me know if you're planning to do so or have questions about it and I can help!

**Comment by james-yoo** [comment]
Hi @PrieureDeSion,
Thanks for your quick response and the clarification. I believe that an approach like GNM will play a key role in autonomous navigation systems and seems to be a lot of room for improvement in the future.
