### ISSUE TITLE
Deployed in the simulation environment

### ISSUE THREAD

**Issue by L1bertad** [PrieureDeSion/drive-any-robot#7]
Hello author, I'm very interested in your research, thanks for your great job.

I see that GNM can be deployed in a simulation environment and I would like to ask you how to deploy it to the simulated environments
?

**Comment by robodhruv** [comment]
Hi,
Deploying the model in simulation should not be any different than deploying on a robot (we have tried setting up in Habitat, CARLA, and a proprietary ROS-based sim). The released code should make it particularly easy to deploy on anything that uses ROS, but you can adapt the files as needed for your simulator of choice.

The relevant files would be in the `deployment` subdir, more information [here](https://github.com/PrieureDeSion/drive-any-robot#deployment). You can skip the robot-specific instructions and follow from "Creating a topological graph".

**Comment by james-yoo** [comment]
@PrieureDeSion,
Speaking of deployment, is it enough to prepare image and odometry topic in rosbag file? And is the accuracy of the odometry an important factor in graph generation?

**Comment by L1bertad** [comment]
Thanks for your quick reply. This helps me a lot.
