### ISSUE TITLE
some question about depolyment with CARLA

### ISSUE THREAD

**Issue by GaHooooo** [PrieureDeSion/drive-any-robot#9]
Thanks for your great job, i want to deploy it with CARLA,can you offer some document about it?

**Comment by GaHooooo** [comment]
when i use conda env create -f deployment/environment.yml,
it has some trouble in solving environment, it use much time and doesn't has result
but i success in conda env create -f train/environment.yml,
did the file deployment/environment.yml correct?

my environment is that:
ubuntu 18.04
cuda 10.2
cudnn 8.7.0
ros melodic 
NVIDIA-SMI 525.78.01

**Comment by jmwang0117** [comment]
> when i use conda env create -f deployment/environment.yml, it has some trouble in solving environment, it use much time and doesn't has result but i success in conda env create -f train/environment.yml, did the file deployment/environment.yml correct?
> 
> my environment is that: ubuntu 18.04 cuda 10.2 cudnn 8.7.0 ros melodic NVIDIA-SMI 525.78.01
hi,
I also encountered this problem, how did you solve it?
